// Auto-generated by generate-data.py — do not edit by hand.
window.SKILL_DATA = {
  "generated": "2026-06-17",
  "code": [
    {
      "name": "accessibility",
      "category": "Design & Frontend",
      "desc": "Use this skill whenever the user asks about web accessibility, a11y, WCAG compliance, ARIA, screen reader support, keyboard navigation, or inclusive design. Triggers include: any mention of accessibility, a11y, WCAG, ARIA, screen readers, keyboard navigation, focus management, color contrast, alt text, semantic HTML, assistive technology, or requests to make a website/app accessible. Also use when reviewing UI code for accessibility issues, building form components, modals, navigation patterns, or any interactive widget. Use this even if the user says 'make this work for everyone' or 'fix the tab order' without explicitly mentioning accessibility.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "accessibility.md",
      "bytes": 15041
    },
    {
      "name": "agent-orchestration",
      "category": "AI & Infra",
      "desc": "Design multi-agent workflows with explicit handoff protocols, output contracts, failure recovery, and context-window management. Use this skill whenever the user mentions multi-agent, agent orchestration, subagents, agent teams, fan-out, parallel agents, agent handoff, supervisor patterns, \"split this across agents\", \"have multiple agents work on this\", \"run these in parallel\", \"can I have two Claudes work on this\". Also trigger when the task naturally decomposes into independent subtasks that could run in parallel, when the user asks about Claude Agent SDK patterns (spawning, context passing, Agent tool), or when Codex tasks need to feed into Claude Code sessions. Distinct from claude-api (SDK-level feature use) and mcp-server-dev (tool plumbing) — this is about COMPOSING agent behavior.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "agent-orchestration.md",
      "bytes": 14133
    },
    {
      "name": "api-design",
      "category": "Design & Frontend",
      "desc": "Use this skill whenever the user asks to design, review, or improve an API. Triggers include: any mention of REST, RESTful, GraphQL, gRPC, API design, endpoints, routes, request/response format, API versioning, pagination, rate limiting, OpenAPI, Swagger, API contracts, or requests involving HTTP methods, status codes, or resource modeling. Also use when the user asks about API best practices, backward compatibility, error responses, or service-to-service communication. Use this even if the user says 'build an endpoint' or 'design the routes' without explicitly mentioning API design principles.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "api-design.md",
      "bytes": 12544
    },
    {
      "name": "cicd-deployment",
      "category": "DevOps & Deploy",
      "desc": "Build CI/CD pipelines and deployment automation using GitHub Actions, Vercel, GitHub Pages, Netlify, Docker, and similar platforms. Use this skill whenever the user mentions CI/CD, continuous integration, continuous deployment, GitHub Actions, deployment pipelines, automated testing, build automation, deploy scripts, \"deploy this\", \"set up CI\", \"automate deployment\", Vercel deployment, GitHub Pages setup, Docker deployment, pre-commit hooks, build caching, deployment previews, zero-downtime deploys, quality gates, Lighthouse CI, accessibility on push. Also trigger for evals-in-CI (AI regression testing on prompt changes) and MCP server pipelines. Distinct from vercel-deploy (direct deploy) and security (one-shot audit) — this is the REPEATABLE pipeline.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "cicd-deployment.md",
      "bytes": 15473
    },
    {
      "name": "cobol",
      "category": "Languages",
      "desc": "Use this skill whenever the user asks to write, review, debug, maintain, or modernize COBOL code. Triggers include: any mention of COBOL, Cobol, .cob, .cbl files, copybooks, JCL, mainframe, CICS, DB2, VSAM, batch processing, or references to legacy system maintenance and migration. Also use when the user asks about COBOL best practices, data division structures, file handling, or modernization strategies for COBOL systems. Use this even if the user says 'mainframe code' or 'legacy batch job' in a context where COBOL is implied.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "cobol.md",
      "bytes": 12222
    },
    {
      "name": "cpp",
      "category": "Languages",
      "desc": "Use this skill whenever the user asks to write, review, debug, refactor, or architect C++ code. Triggers include: any mention of C++, CPP, .cpp, .hpp, .h files, CMake, Makefile, STL, templates, RAII, smart pointers, or requests involving C++-specific patterns like move semantics, constexpr, concepts, or coroutines. Also use when the user asks about C++ best practices, memory management, build systems, or performance-critical systems programming. Use this even if the user says 'write something fast' or 'systems-level code' in a context where C++ is the established language.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "cpp.md",
      "bytes": 11219
    },
    {
      "name": "critique",
      "category": "Code Quality",
      "desc": "Evaluate quality and identify weaknesses in code, plans, prompts, or designs. Findings first, evidence first. Diagnose and recommend without rewriting. Use when you need honest assessment of an artifact before shipping or iterating.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "critique.md",
      "bytes": 2268
    },
    {
      "name": "debug",
      "category": "Code Quality",
      "desc": "Diagnose bugs, failures, and unexpected behavior in code and systems. Find root cause, propose fixes, identify side effects, and prevent recurrence. Use when something is broken and you need to know why before you fix it.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "debug.md",
      "bytes": 3318
    },
    {
      "name": "decision",
      "category": "Workflow & Process",
      "desc": "Turn ambiguity into clear choices. Explore options, analyze trade-offs, recommend a path forward with reasoning and consequences. Use when you're stuck between options and need to commit.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "decision.md",
      "bytes": 2163
    },
    {
      "name": "develop-web-game",
      "category": "Games",
      "desc": "Build or iterate on a web game (HTML/JS) with a reliable development and testing loop. Implement small changes, validate with screenshots and text state, review console errors. Use when building browser-based games.",
      "claude": true,
      "codex": true,
      "multiFile": true,
      "file": "develop-web-game.md",
      "bytes": 4430
    },
    {
      "name": "eval-frameworks",
      "category": "AI & Infra",
      "desc": "Design and run evaluation frameworks for AI outputs — assertions, regression testing, prompt benchmarking, judge-model grading, CI integration. Use this skill whenever the user mentions evals, evaluations, testing AI outputs, benchmarking prompts, regression testing for LLMs, grading model responses, \"is this prompt better\", \"how do I test this\", assertion design, eval sets, judge models, golden responses, or wants to verify that an AI feature still works after a prompt change. Also trigger on \"how do I know this won't break\", \"test my prompt\", \"compare these two versions\", or CI for AI features. Distinct from traditional unit testing (pytest, vitest) and from skill-creator (which has eval logic baked in) — this is general-purpose evaluation of non-deterministic AI outputs.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "eval-frameworks.md",
      "bytes": 15118
    },
    {
      "name": "extract",
      "category": "Workflow & Process",
      "desc": "Pull structured action items, decisions, findings, and follow-ups from unstructured content. Use when you need to turn messy input into a clean checklist or database entry.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "extract.md",
      "bytes": 2553
    },
    {
      "name": "frontend-design",
      "category": "Design & Frontend",
      "desc": "Build or restyle production frontend UI with a distinctive visual direction. Use for landing pages, dashboards, app surfaces, components, HTML/CSS layouts, or frontend polish work when design quality matters. Preserve existing design systems unless the user explicitly asks for a redesign.",
      "claude": true,
      "codex": true,
      "multiFile": true,
      "file": "frontend-design.md",
      "bytes": 5079
    },
    {
      "name": "frontend-review",
      "category": "Design & Frontend",
      "desc": "Review frontend work for design quality, UX, accessibility, responsiveness, performance, and implementation risk. Findings first, evidence first, fixes second. Use when the user asks for critique, QA, polish recommendations, or a frontend review without asking for a rebuild.",
      "claude": true,
      "codex": true,
      "multiFile": true,
      "file": "frontend-review.md",
      "bytes": 3379
    },
    {
      "name": "functional-architecture",
      "category": "Design & Frontend",
      "desc": "Design clean, scalable application logic, state management, and integration boundaries. Use for refactors, frontend architecture, typed data flow, store design, hooks, adapters, and modular app structure where maintainability matters.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "functional-architecture.md",
      "bytes": 3985
    },
    {
      "name": "game-engine-primitives",
      "category": "Games",
      "desc": "Reusable building blocks for vanilla 2D web games — game loop, input, collision, camera, FSM, sprite animation, physics tuning, enemy AI, HUD, and in-game debug overlay. Use when adding any of these systems to a 2D web game, or when the broader develop-web-game skill needs a specific primitive. Trigger on game loop, requestAnimationFrame, delta time, input mapping, keyboard, hitbox, AABB, collision, camera follow, screen shake, state machine, FSM, sprite sheet, animation frames, gravity, friction, jump tuning, game feel, enemy AI, patrol, chase, HUD, score, health bar, FPS counter, debug overlay.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "game-engine-primitives.md",
      "bytes": 11616
    },
    {
      "name": "gap-analysis",
      "category": "Code Quality",
      "desc": "Identify missing components, unaddressed risks, and structural gaps in plans, specs, systems, and checklists. Answers \"what should be here but isn't?\" Use before committing to an implementation plan or shipping a feature.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "gap-analysis.md",
      "bytes": 2475
    },
    {
      "name": "go",
      "category": "Languages",
      "desc": "Use this skill whenever the user asks to write, review, debug, refactor, or architect Go code. Triggers include: any mention of Go, Golang, .go files, goroutines, channels, go modules, go routines, or requests involving Go-specific patterns like interfaces, error handling, or concurrency with goroutines. Also use when the user asks about Go best practices, the standard library, microservices in Go, or CLI tools in Go. Use this even if the user says 'write a microservice' or 'build a CLI' in a context where Go is the established language.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "go.md",
      "bytes": 14265
    },
    {
      "name": "gsap",
      "category": "Design & Frontend",
      "desc": "Use this skill whenever the user asks to write, review, debug, or architect animations using GSAP (GreenSock Animation Platform). Triggers include: any mention of GSAP, GreenSock, ScrollTrigger, Flip plugin, MorphSVG, DrawSVG, SplitText, MotionPath, ScrollSmoother, useGSAP hook, gsap.timeline, gsap.to, scrub animations, pin sections, or animation timelines. Also trigger on requests for scroll driven animation, sequenced timeline choreography, SVG path drawing, layout transition animations (FLIP technique), shared element transitions, character by character text reveals, or any animation more complex than a single CSS transition. Use this skill even if the user says 'animate this', 'add motion', 'scroll animation', 'morph this SVG', or 'fancy reveal' in any context where the answer is GSAP. This skill covers the post 2024 reality where every GreenSock plugin including SplitText, MorphSVG, DrawSVG, and ScrollSmoother is free for commercial use.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "gsap.md",
      "bytes": 19467
    },
    {
      "name": "java",
      "category": "Languages",
      "desc": "Use this skill whenever the user asks to write, review, debug, refactor, or architect Java code. Triggers include: any mention of Java, .java files, JVM, Spring, Maven, Gradle, JUnit, Jakarta EE, or requests involving Java-specific patterns like generics, streams, records, sealed classes, or virtual threads. Also use when the user asks about Java best practices, dependency injection, build tooling, or JVM performance tuning. Use this even if the user just says 'write a class' or 'build a service' in a context where Java is the established language.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "java.md",
      "bytes": 10906
    },
    {
      "name": "javascript",
      "category": "Languages",
      "desc": "Use this skill whenever the user asks to write, review, debug, refactor, or architect JavaScript or TypeScript code. Triggers include: any mention of JavaScript, JS, TypeScript, TS, .js, .ts, .jsx, .tsx files, Node.js, npm, Bun, Deno, React, Vue, Svelte, Express, Next.js, or requests involving JS-specific patterns like closures, promises, async/await, or the event loop. Also use when the user asks about JS best practices, bundling, runtime environments, or frontend/backend JS architecture. Use this even if the user says 'web app' or 'API' in a context where JavaScript/TypeScript is the established language.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "javascript.md",
      "bytes": 11295
    },
    {
      "name": "log-this-now",
      "category": "Workflow & Process",
      "desc": "Use when Dave says 'log this now', 'log the session', asks for a traffic light / traffic-light status on session work, or asks to verify-and-log a work session. This skill verifies the real status of the work against a source of truth, renames the session in Dave's format, outputs a compact in-chat traffic-light status block, and writes exactly one log row to the correct Notion database (plus a Bug Backlog row when the session was mainly bug/triage/QA/debug work). Core rule: query before reporting; never claim Complete or Logged without verification.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "log-this-now.md",
      "bytes": 7316
    },
    {
      "name": "mcp-server-dev",
      "category": "AI & Infra",
      "desc": "Build, test, and deploy MCP (Model Context Protocol) servers that give Claude, Codex, and other AI agents access to external tools and data. Use this skill whenever the user mentions MCP, Model Context Protocol, building a tool server, creating a connector, \"hook Claude into X\", \"give Claude access to Y\", writing tool schemas, MCP Inspector, stdio transport, SSE transport, FastMCP. Also trigger when the user says \"wire this up\", \"connect Claude to my API\", \"build a tool for this\", or \"I want Claude to be able to [action]\" where the action requires an external service. Distinct from claude-api (SDK usage), update-config (configuring an existing server), and hooks (lifecycle enforcement). This is for BUILDING a new server.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "mcp-server-dev.md",
      "bytes": 13942
    },
    {
      "name": "motion-choreography",
      "category": "Design & Frontend",
      "desc": "Orchestrate high-performance UI motion, staggered arrivals, hover physics, and gesture states. Use for interface animation systems, transition design, interaction feedback, and motion polish that reinforces hierarchy without harming performance.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "motion-choreography.md",
      "bytes": 3434
    },
    {
      "name": "notion-connector-markdown",
      "category": "Notion & Media",
      "desc": "Verified reference for the exact markdown syntax the Notion connector accepts when creating or editing pages. Use whenever authoring or editing Notion pages through the connector (creating pages, updating page content, inserting blocks). Covers which blocks render (callout, columns, toggle via details/summary, table, block and inline equations, mermaid diagrams, tabs, table of contents, synced block), which are escaped and cannot be created (the bare toggle tag, bookmark, video, embed, button, AI blocks, AI meeting notes), the callout color palette, and operational gotchas such as preferring targeted edits over full rewrites, matching unescaped text in update operations, and the tabs first-line-is-the-title rule. Trigger on any Notion page formatting, block syntax, callouts, tabs, columns, or a block that did not render as expected.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "notion-connector-markdown.md",
      "bytes": 5048
    },
    {
      "name": "notion-db-prompts",
      "category": "Notion & Media",
      "desc": "Standard for working with the Notion database \"DB | Prompts\" (id 255255fc-8f44-80f2-a90e-c15b81f80f93). Trigger when the user adds/edits/queries prompts in DB | Prompts; asks to audit, clean up, dedup, rename, classify, or backfill it; references the prompt library, Naming Suggestion, Review Flag, or the 🧹 Cleanup flag; or asks to record a prompt audit. Encodes the canonical schema, naming convention, the ideal-row definition of done, the hygiene anti-patterns found in the 2026-06-13 sweep, access, and the audit procedure (flag → record to the 🧪 Audits hub → CSV manifest). Derived from a 378-row, 45-agent hygiene audit.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "notion-db-prompts.md",
      "bytes": 9650
    },
    {
      "name": "python",
      "category": "Languages",
      "desc": "Use this skill whenever the user asks to write, review, debug, refactor, or architect Python code. Triggers include: any mention of Python, .py files, pip, poetry, Django, Flask, FastAPI, pandas, numpy, pytest, or requests involving Python-specific patterns like decorators, generators, context managers, type hints, or async/await. Also use when the user asks about Python best practices, packaging, virtual environments, or performance optimization. Use this even if the user just says 'write a script' or 'automate this' in a context where Python is the established language.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "python.md",
      "bytes": 9937
    },
    {
      "name": "rag-knowledge-systems",
      "category": "AI & Infra",
      "desc": "Design and build retrieval-augmented generation (RAG) pipelines that connect AI agents to knowledge bases, document stores, and structured data. Use this skill whenever the user mentions RAG, retrieval-augmented generation, embeddings, vector databases, semantic search, knowledge graphs, document retrieval, chunking strategies, \"search my docs\", \"query my knowledge base\", \"make this searchable by Claude\", ChromaDB, Pinecone, LanceDB, pgvector, FAISS, embedding models, reranking, hybrid search, or \"Claude doesn't know about my [internal docs / codebase / wiki / Notion workspace]\". Also trigger on \"help me find things in my notes\" or \"make my project docs searchable\". Distinct from agent-orchestration (workflow shape) and mcp-server-dev (tool plumbing) — this is the KNOWLEDGE layer.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "rag-knowledge-systems.md",
      "bytes": 14815
    },
    {
      "name": "rust",
      "category": "Languages",
      "desc": "Use this skill whenever the user asks to write, review, debug, refactor, or architect Rust code. Triggers include: any mention of Rust, .rs files, Cargo, crates, the borrow checker, lifetimes, traits, async Rust, tokio, actix, axum, wasm, or requests involving Rust-specific patterns like ownership, borrowing, pattern matching, or zero-cost abstractions. Also use when the user asks about Rust best practices, memory safety, concurrency, or systems programming in Rust. Use this even if the user says 'safe systems code' or 'no garbage collector' in a context where Rust is implied.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "rust.md",
      "bytes": 13815
    },
    {
      "name": "security",
      "category": "Code Quality",
      "desc": "Use this skill whenever the user asks about application security, secure coding, authentication, authorization, or vulnerability prevention. Triggers include: any mention of security, auth, OAuth, JWT, session management, OWASP, XSS, CSRF, SQL injection, input validation, encryption, hashing, secrets management, CORS, CSP, penetration testing, or security headers. Also use when reviewing code for security issues, designing auth flows, handling sensitive data, or when the user asks about securing an API, web app, or service. Use this even if the user says 'make this secure' or 'add authentication' without using specific security terminology.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "security.md",
      "bytes": 14465
    },
    {
      "name": "session-report",
      "category": "Workflow & Process",
      "desc": "Generate a structured end-of-session report covering accomplishments, decisions, action items, deliverables, and per-project status — then log results to Notion. Use this skill whenever the user asks to wrap up a session, produce a session summary, create a session report, log what happened, or says anything like \"session report\", \"wrap up\", \"capture this session\", \"end of session\", \"what did we do\", \"log this to Notion\", or \"close out\". Also trigger when the user pastes a long capture-protocol-style prompt requesting a structured review of the conversation. This skill is distinct from capture-protocol (which logs individual findings) — this produces a comprehensive, multi-section report of the entire session.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "session-report.md",
      "bytes": 7187
    },
    {
      "name": "skill-scaffold",
      "category": "Workflow & Process",
      "desc": "",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "skill-scaffold.md",
      "bytes": 4424
    },
    {
      "name": "slicemo-workflow",
      "category": "Notion & Media",
      "desc": "Enforce the workflow for generating matching icon/banner/cover sets, slicing the batched grid, and assigning slices to Notion page covers via NATIVE Notion file upload (no imgbb). Trigger when the user mentions generating a matching set of icons, banners, covers, thumbnails, or tiles; references an imagegen prompt for a batch; mentions slicing a grid image; references slice_grid.py, notion_covers.py, set_notion_covers.py, slicemo, Slicemo.app, slicemo_gui.py, or the cover-workflow-runbook; asks to apply/assign banners or covers to a Notion database; or hands over a folder of pre-sliced banners to apply. Also trigger on phrasings like \"apply these banners as covers\", \"batch covers for my DB\", \"consistent icons for these pages\", \"make 15 matching banners\", \"split this grid and push to Notion\", or \"generate then slice and assign\". Owns the gate discipline (dry-run, pairing confirm, results log), the imagegen prompt anatomy, and content-based banner→page matching.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "slicemo-workflow.md",
      "bytes": 13256
    },
    {
      "name": "sql",
      "category": "Languages",
      "desc": "Use this skill whenever the user asks to write, review, debug, optimize, or design SQL queries or database schemas. Triggers include: any mention of SQL, queries, SELECT, JOIN, indexes, database schema, migrations, PostgreSQL, Postgres, MySQL, MariaDB, SQLite, SQL Server, MSSQL, Oracle, stored procedures, views, CTEs, window functions, or requests involving database performance, query optimization, or data modeling. Also use when the user asks about normalization, indexing strategy, transaction isolation, or database design. Use this even if the user says 'pull this data' or 'fix this query' in a context where SQL is implied.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "sql.md",
      "bytes": 14164
    },
    {
      "name": "system-builder",
      "category": "Workflow & Process",
      "desc": "Design structured workflows, pipelines, and systems. Define components with single responsibility, map data flow, specify interfaces, and clarify dependencies. Use when building infrastructure, automation, or multi-service architectures.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "system-builder.md",
      "bytes": 2636
    },
    {
      "name": "technical-drawing",
      "category": "Notion & Media",
      "desc": "Produce and review technical drawings (floor plans, electrical, lighting, network/data, AV, mechanical, RCP, structural overlays) under a strict \"existing conditions first\" discipline. Use this skill whenever the user asks to draft, refine, mark up, overlay, or audit a floor plan, site plan, AV install packet, electrical sheet, lighting plan, data drop layout, rack elevation, low voltage diagram, reflected ceiling plan, or any sheet a contractor, AV tech, electrician, or installer would carry into the field. Also trigger on requests like \"clean up this floor plan,\" \"add an overlay,\" \"draw the cable runs,\" \"show speaker coverage,\" \"where do the data drops go,\" \"make this look like an install sheet,\" or anything involving a source drawing that needs interpretation without invention. The core rule this skill enforces: the source drawing is authoritative truth. Geometry never drifts, structure never moves, infrastructure is never fabricated, and assumptions are always tagged. Do NOT use this skill for marketing graphics, concept renders, mood boards, or \"AI generated space\" visuals.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "technical-drawing.md",
      "bytes": 13188
    },
    {
      "name": "update-promptlab-notion",
      "category": "Notion & Media",
      "desc": "Standard + canonical page map for updating the PromptLab / Prompt Lab project in Notion. Trigger when the user asks to update Prompt Lab's Notion, record/post a project status update, change its Health/Blocker/Status/Next Action, log build or release state, reconcile the project record after a work session, or find \"the canonical Prompt Lab Notion page(s)\". Encodes the canonical page map (records, DBs, living docs, archived-do-not-touch), the Canonical Hub row property schema, the exact update recipe (query → update_properties → prepend dated callout), the status-callout convention, governance guardrails, and known doc-link debt to fix.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "update-promptlab-notion.md",
      "bytes": 8411
    },
    {
      "name": "vercel-cost-guard",
      "category": "DevOps & Deploy",
      "desc": "Use when deploying, unpausing, promoting, debugging, or reviewing Vercel projects with API routes, Fluid Compute, billing, provider proxies, webhooks, telemetry, cron jobs, queues, observability, analytics, usage spikes, or cost concerns. Trigger on Vercel billing, timeout, 504, function duration, Fluid Compute, unexpected charges, serverless, edge function, production deploy safety, API route spend, or cost containment.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "vercel-cost-guard.md",
      "bytes": 4889
    },
    {
      "name": "vercel-deploy",
      "category": "DevOps & Deploy",
      "desc": "Deploy applications and websites to Vercel. Use when the user requests deployment actions like \"deploy my app\", \"push this live\", or \"create a preview deployment\".",
      "claude": true,
      "codex": true,
      "multiFile": true,
      "file": "vercel-deploy.md",
      "bytes": 3353
    },
    {
      "name": "video-pipeline",
      "category": "Notion & Media",
      "desc": "Turn a brief into a complete, internally-consistent video production pack — script, teleprompter, shot plan, packaging — with a forced fact-check (accuracy) gate and a privacy gate before anything is called \"publish-ready.\" Use this skill whenever the user wants to script, plan, or fact-check a scripted video: an explainer, tutorial, walkthrough, product review, demo, or vlog-with-script. It triggers on phrases like \"write a video script\", \"make a teleprompter\", \"build a shot plan\", \"shot list\", \"voiceover script\", \"VO script\", \"fact-check this video\", \"is this claim accurate\", \"production pack\", \"YouTube script\", \"video outline\", \"reconcile runtime\", \"trim the runtime\", or \"I'm making a video about X\". Also trigger when the user has a script and wants any derived view regenerated (teleprompter or shot plan), wants claims verified against sources, or wants a publish-readiness check. Err toward triggering for any scripted-video authoring or verification task — you can detect irrelevance internally, but you can't activate if the description doesn't match. Do NOT trigger for actual video editing/rendering, thumbnail image generation, or uploading to a platform — this produces text/markdown artifacts and capture instructions only.",
      "claude": true,
      "codex": true,
      "multiFile": false,
      "file": "video-pipeline.md",
      "bytes": 23731
    }
  ],
  "notion": [
    {
      "name": "Chat Rename Prompt 🏷️",
      "category": "Productivity",
      "status": "Live",
      "trigger": "Chat Rename Prompt — Home Rules Format",
      "summary": ""
    },
    {
      "name": "Fix & Add Emojis for Categories 😊",
      "category": "Formatting",
      "status": "Live",
      "trigger": "Fix & Add Emojis for Categories",
      "summary": ""
    },
    {
      "name": "Proofread ✅",
      "category": "Writing",
      "status": "Live",
      "trigger": "Proofread",
      "summary": ""
    },
    {
      "name": "Add Formatting 🎨",
      "category": "Formatting",
      "status": "Live",
      "trigger": "Add Formatting",
      "summary": ""
    },
    {
      "name": "AI Orchestrator 🎛️",
      "category": "AI / Prompts",
      "status": "Live",
      "trigger": "Orchestrate AI Stack (Route Work)",
      "summary": ""
    },
    {
      "name": "Apply Detailed Formatting 📐",
      "category": "Formatting",
      "status": "Live",
      "trigger": "Apply Detailed Formatting",
      "summary": ""
    },
    {
      "name": "Convert to Table 📊",
      "category": "Formatting",
      "status": "Live",
      "trigger": "Convert to Table",
      "summary": ""
    },
    {
      "name": "Create Table with Model Entries 📊",
      "category": "Productivity",
      "status": "Live",
      "trigger": "Create Table with Model Entries",
      "summary": ""
    },
    {
      "name": "Debug to Fix 🐛",
      "category": "Dev",
      "status": "Live",
      "trigger": "Debug to Fix",
      "summary": ""
    },
    {
      "name": "Develop, Group and Create Prompts 🧩",
      "category": "AI / Prompts",
      "status": "Live",
      "trigger": "Develop, Group & Create Prompts",
      "summary": ""
    },
    {
      "name": "Draft Run of Show 🎬",
      "category": "AV / Production",
      "status": "Live",
      "trigger": "Draft Run of Show",
      "summary": ""
    },
    {
      "name": "Expand Selection 📖",
      "category": "Writing",
      "status": "Live",
      "trigger": "Expand Selection",
      "summary": ""
    },
    {
      "name": "Explain 💬",
      "category": "Productivity",
      "status": "Live",
      "trigger": "Explain",
      "summary": ""
    },
    {
      "name": "Fill Data from Records into Template 📋",
      "category": "Productivity",
      "status": "Live",
      "trigger": "Fill Data from Records into Template",
      "summary": ""
    },
    {
      "name": "Generate Page Banner Prompt 🖼️",
      "category": "AI / Prompts",
      "status": "Live",
      "trigger": "Generate Page Banner Prompt",
      "summary": ""
    },
    {
      "name": "Generate README 📝",
      "category": "Dev",
      "status": "Live",
      "trigger": "Generate README",
      "summary": ""
    },
    {
      "name": "Generate Shot Plan 🎬",
      "category": "AV / Production",
      "status": "Live",
      "trigger": "Generate Shot Plan",
      "summary": ""
    },
    {
      "name": "Improve Writing ✏️",
      "category": "Writing",
      "status": "Live",
      "trigger": "Improve Writing",
      "summary": ""
    },
    {
      "name": "Make Toggle Lists 🔽",
      "category": "Formatting",
      "status": "Live",
      "trigger": "Make Toggle Lists (Expanded)",
      "summary": ""
    },
    {
      "name": "Notion Page Aesthetic Design 🎨",
      "category": "Formatting",
      "status": "Live",
      "trigger": "Design Page (Aesthetic Direction)",
      "summary": ""
    },
    {
      "name": "Organize and Enhance Page 🗂️",
      "category": "Formatting",
      "status": "Live",
      "trigger": "Organize & Enhance Page",
      "summary": ""
    },
    {
      "name": "Page Structuring and Visual Formatting 🖼️",
      "category": "Formatting",
      "status": "Live",
      "trigger": "Organize, Add Colors & Callouts",
      "summary": ""
    },
    {
      "name": "Parse Tech Rider 🎛️",
      "category": "AV / Production",
      "status": "Live",
      "trigger": "Parse Tech Rider",
      "summary": ""
    },
    {
      "name": "Refactor Page Layout",
      "category": "Formatting",
      "status": "Live",
      "trigger": "Reformat page / two column layout / improve visual hierarchy",
      "summary": "Refactors Notion pages into polished, two column layouts while preserving meaning and improving live usability."
    },
    {
      "name": "Reformat ⚙️",
      "category": "Formatting",
      "status": "Live",
      "trigger": "Reformat",
      "summary": ""
    },
    {
      "name": "Rename DB Entries",
      "category": "Productivity",
      "status": "Live",
      "trigger": "Naming hygiene / audit names / naming audit",
      "summary": ""
    },
    {
      "name": "Review and Suggest Fixes 🔍",
      "category": "Dev",
      "status": "Live",
      "trigger": "Review & Suggest Fixes",
      "summary": ""
    },
    {
      "name": "Sort Inbox 🗂️",
      "category": "Productivity",
      "status": "Live",
      "trigger": "Sort Inbox",
      "summary": ""
    },
    {
      "name": "Summarize Page to Bullet Points 📊",
      "category": "Productivity",
      "status": "Live",
      "trigger": "Summarize Page to Bullet Points",
      "summary": ""
    },
    {
      "name": "UI HUD Builder",
      "category": "Dev",
      "status": "Live",
      "trigger": "UI HUD Builder / add HUD / health bar / display score",
      "summary": "Builds responsive, accessible web game HUD modules with stable render and update exports."
    },
    {
      "name": "Write as Dave ✏️",
      "category": "Writing",
      "status": "Live",
      "trigger": "Write as Dave",
      "summary": "Drafts concise, register-aware writing in Dave Robertson's voice while preserving facts and review gates."
    },
    {
      "name": "Camera Controls 🎥",
      "category": "Dev",
      "status": "Draft",
      "trigger": "camera-controls",
      "summary": ""
    },
    {
      "name": "Collision 2D 💥",
      "category": "Dev",
      "status": "Draft",
      "trigger": "collision-2d",
      "summary": ""
    },
    {
      "name": "Debug Tooling 🐛",
      "category": "Dev",
      "status": "Draft",
      "trigger": "debug-tooling",
      "summary": ""
    },
    {
      "name": "Enemy AI Patterns 🤖",
      "category": "Dev",
      "status": "Draft",
      "trigger": "enemy-ai-patterns",
      "summary": ""
    },
    {
      "name": "Game Loop Scaffold 🎮",
      "category": "Dev",
      "status": "Draft",
      "trigger": "game-loop-scaffold",
      "summary": ""
    },
    {
      "name": "Ideas for New Skills 📝",
      "category": "Uncategorized",
      "status": "Draft",
      "trigger": "",
      "summary": "Scratchpad / backlog of skill ideas to build."
    },
    {
      "name": "Input System 🎮",
      "category": "Dev",
      "status": "Draft",
      "trigger": "input-system",
      "summary": ""
    },
    {
      "name": "Physics Tuning 🎮",
      "category": "Dev",
      "status": "Draft",
      "trigger": "physics-tuning",
      "summary": ""
    },
    {
      "name": "Sprite Animation 🎮",
      "category": "Dev",
      "status": "Draft",
      "trigger": "sprite-animation",
      "summary": ""
    },
    {
      "name": "State Machine ⚙️",
      "category": "Dev",
      "status": "Draft",
      "trigger": "state-machine",
      "summary": ""
    },
    {
      "name": "Traffic Light Status Check",
      "category": "AI / Prompts",
      "status": "Draft",
      "trigger": "is this done? / status check",
      "summary": "Reports a verified completion status as a single traffic light by querying the source of truth first."
    },
    {
      "name": "AI Skills in Notion 🤖",
      "category": "AI / Prompts",
      "status": "Archived",
      "trigger": "",
      "summary": ""
    },
    {
      "name": "Notion Skill Library 🧰",
      "category": "AI / Prompts",
      "status": "Archived",
      "trigger": "",
      "summary": ""
    },
    {
      "name": "Revise ✏️",
      "category": "Writing",
      "status": "Archived",
      "trigger": "Revise",
      "summary": ""
    },
    {
      "name": "Implementation Plan 📄",
      "category": "Dev",
      "status": "Unset",
      "trigger": "",
      "summary": ""
    }
  ]
};
